[versions]
graphql-java = "16.2"

[libraries]
# Micronaut
micronaut-jackson-databind = { module = "io.micronaut:micronaut-jackson-databind" }

graphql-java = { module = "com.graphql-java:graphql-java", version.ref = "graphql-java" }
