[versions]
managed-graphql-java = "16.2"

[libraries]
# Micronaut
micronaut-jackson-databind = { module = "io.micronaut:micronaut-jackson-databind" }

managed-graphql-java = { module = "com.graphql-java:graphql-java", version.ref = "managed-graphql-java" }
